#!/usr/bin/env python3
"""Generate deterministic embedded dashboard assets.

Reads authoritative HTML from mcp2515_dashboard_ui.src.h, gzips it with a
fixed timestamp, and writes mcp2515_dashboard_ui.h with both:
  - DASH_HTML[]   (raw HTML, for native builds and debugging)
  - DASH_HTML_GZ[] / DASH_HTML_GZ_LEN  (gzip-compressed for HTTP send)

Generation deliberately uses only Python's standard library. Output must not
depend on optional host minifiers or executables.
"""
import gzip
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "include" / "web" / "mcp2515_dashboard_ui.src.h"
DST = ROOT / "include" / "web" / "mcp2515_dashboard_ui.h"


text = SRC.read_text() if SRC.exists() else DST.read_text()
m = re.search(r'R"HTML\((.*)\)HTML";', text, re.DOTALL)
if not m:
    print("no HTML payload found", file=sys.stderr)
    sys.exit(1)

html = m.group(1)
raw_len = len(html)
gz = gzip.compress(html.encode("utf-8"), compresslevel=9, mtime=0)
gz_len = len(gz)


def hex_array(data: bytes, width: int = 16) -> str:
    out = []
    for i in range(0, len(data), width):
        chunk = data[i : i + width]
        out.append(",".join(f"0x{b:02x}" for b in chunk))
    return ",\n    ".join(out)


body = []
body.append("// Generated by scripts/minify_dashboard.py. Edit mcp2515_dashboard_ui.src.h.")
body.append("#pragma once")
body.append("#ifdef ESP_PLATFORM")
body.append('#include "platform/espidf_runtime.h"')
body.append("#else")
body.append("#include <Arduino.h>")
body.append("#endif")
body.append("#include <stddef.h>")
body.append("#include <stdint.h>")
body.append("")
body.append("#ifndef ESP_PLATFORM")
body.append('static const char DASH_HTML[] PROGMEM = R"HTML(' + html + ')HTML";')
body.append("#endif")
body.append("")
body.append("static const uint8_t DASH_HTML_GZ[] PROGMEM = {")
body.append("    " + hex_array(gz))
body.append("};")
body.append(f"static constexpr size_t DASH_HTML_GZ_LEN = {gz_len};")
body.append("")

DST.write_text("\n".join(body))

print(
    f"dashboard: {raw_len} bytes raw, {gz_len} bytes gzip "
    f"({100 * gz_len / raw_len:.1f}% of raw)"
)
